"use client";

import { ArrowUpRight, ChevronRight, FileText, Search, Sparkles } from "lucide-react";
import { useState } from "react";

import { DocumentSurface, FitScore, PageHeader, Panel, SkillChip, StatusChip, StructuredRow } from "./primitives";

const jobs = [
  { role: "Senior Product Engineer", company: "Northstar Labs", location: "Remote · US", source: "Curated", score: 87, skills: ["TypeScript", "Next.js", "Systems"] },
  { role: "Staff Frontend Engineer", company: "Civic Thread", location: "New York · Hybrid", source: "Radar", score: 79, skills: ["React", "Design systems", "GraphQL"] },
  { role: "Platform Engineer", company: "Field Notes", location: "Remote · US", source: "Radar", score: 68, skills: ["Kubernetes", "Postgres" ] },
];

export function DashboardView({ onOpenCoach, onNavigate }: { onOpenCoach: () => void; onNavigate: (path: string) => void }) {
  return <div className="view-stack">
    <PageHeader eyebrow="Tuesday, September 8" title="Good morning, Alex." description="Your career file is up to date. Here is what deserves your attention." action={<button className="button-primary" onClick={onOpenCoach}><Sparkles aria-hidden="true" /> Ask Coach</button>} />
    <div className="attention-grid">
      <Panel className="attention-panel"><div className="panel-kicker">Next action</div><h2>Review your Northstar match</h2><p>This role has the strongest alignment with your verified systems experience.</p><div className="panel-footer"><FitScore score={87} onWhy={onOpenCoach} /><button className="text-action" onClick={() => onNavigate("/jobs")}>Open Job Radar <ArrowUpRight aria-hidden="true" /></button></div></Panel>
      <Panel><div className="panel-kicker">Profile signal</div><h2>One gap is holding back your profile</h2><p>Three recent roles ask for distributed systems language. You have the evidence; it is not surfaced yet.</p><button className="text-action" onClick={() => onNavigate("/career-profile")}>Review profile evidence <ChevronRight aria-hidden="true" /></button></Panel>
    </div>
    <div className="section-heading"><div><p className="eyebrow">Curated opportunities</p><h2>Worth a closer look</h2></div><button className="button-secondary" onClick={() => onNavigate("/jobs")}>View all</button></div>
    <Panel className="table-panel"><div className="job-table-head"><span>Role</span><span>Location</span><span>Fit</span><span>Skills</span></div>{jobs.map((job) => <div className="job-row" key={job.role}><div><strong>{job.role}</strong><span>{job.company}</span></div><span className="muted">{job.location}</span><FitScore score={job.score} onWhy={onOpenCoach} /><div className="skill-list">{job.skills.slice(0, 2).map((skill) => <SkillChip key={skill}>{skill}</SkillChip>)}</div></div>)}</Panel>
  </div>;
}

export function JobsView({ onOpenCoach }: { onOpenCoach: () => void }) {
  const [selected, setSelected] = useState(0);
  return <div className="view-stack"><PageHeader eyebrow="Core / Job Radar" title="Job Radar" description="A considered shortlist, ranked by evidence and fit — not volume." action={<button className="button-primary"><Search aria-hidden="true" /> Search roles</button>} /><Panel className="table-panel"><div className="job-table-head"><span>Role / Company</span><span>Location</span><span>Source</span><span>Fit + explanation</span></div>{jobs.map((job, index) => <button type="button" className={`job-row job-row-button ${selected === index ? "row-selected" : ""}`} key={job.role} onClick={() => setSelected(index)}><div><strong>{job.role}</strong><span>{job.company}</span></div><span className="muted">{job.location}</span><span className="muted">{job.source}</span><div><FitScore score={job.score} onWhy={onOpenCoach} /><div className="skill-list">{job.skills.map((skill, i) => <SkillChip key={skill} matched={i !== 2}>{skill}</SkillChip>)}</div></div></button>)}</Panel><Panel className="explanation-panel"><div><p className="panel-kicker">Why this matches</p><h2>{jobs[selected]?.role}</h2><p>Strong evidence across product delivery and platform ownership. The score is based on your verified profile, not inferred credentials.</p></div><div className="explanation-list"><StructuredRow label="Evidence" value="4 of 5 signals" /><StructuredRow label="Skill alignment" value="High" /><StructuredRow label="One gap" value="Event-driven systems" /></div></Panel></div>;
}

export function ResumeView() { return <div className="view-stack"><PageHeader eyebrow="Core / Resume Studio" title="Resume Studio" description="Shape evidence into focused documents. Review suggestions before they become edits." action={<button className="button-primary"><FileText aria-hidden="true" /> New version</button>} /><div className="split-view"><Panel><div className="section-heading"><div><p className="eyebrow">Resume profiles</p><h2>Targeted documents</h2></div></div>{["Platform Engineering", "Product Engineering", "General profile"].map((name, i) => <div className="list-row" key={name}><div><strong>{name}</strong><span>Last edited {i + 2} days ago</span></div><StatusChip tone={i === 0 ? "success" : "neutral"}>{i === 0 ? "Ready" : "Draft"}</StatusChip></div>)}</Panel><DocumentSurface><p className="document-label">Preview · Platform Engineering</p><h2>Alex Morgan</h2><p className="document-role">Product-minded systems engineer</p><hr /><h3>Experience</h3><p>Builds dependable software systems and makes complex work legible to the people who use them.</p><div className="document-note"><Sparkles aria-hidden="true" /><span>Coach suggestion: surface your event-driven architecture evidence here.</span></div></DocumentSurface></div></div>; }

export function ProfileView() { return <div className="view-stack"><PageHeader eyebrow="Core / Career Profile" title="Career Profile" description="The structured record that powers every CareerOS decision." action={<button className="button-secondary">Edit profile</button>} /><DocumentSurface><div className="profile-identity"><div className="avatar avatar-large">AM</div><div><p className="eyebrow">Professional record</p><h2>Alex Morgan</h2><p>Product-minded systems engineer · New York / Remote</p></div></div><div className="profile-grid"><StructuredRow label="Experience" value="8 years" /><StructuredRow label="Education" value="B.S. Computer Science" /><StructuredRow label="Focus" value="Systems · Product" /><StructuredRow label="Availability" value="Open to conversations" /></div><hr /><h3>Verified skills</h3><div className="skill-list">{["TypeScript", "React", "PostgreSQL", "Distributed systems", "Product strategy"].map((skill) => <SkillChip key={skill}>{skill}</SkillChip>)}</div></DocumentSurface></div>; }

export function ApplicationsView() { return <div className="view-stack"><PageHeader eyebrow="Core / Applications" title="Applications" description="Keep momentum visible without turning your search into a spreadsheet." action={<button className="button-primary">Log application</button>} /><Panel className="table-panel"><div className="job-table-head"><span>Company / role</span><span>Status</span><span>Last activity</span><span>Next action</span></div>{[["Northstar Labs", "Senior Product Engineer", "Interview", "Yesterday", "Prepare story"],["Civic Thread", "Staff Frontend Engineer", "Applied", "Sep 4", "Follow up Friday"],["Field Notes", "Platform Engineer", "Saved", "Sep 2", "Tailor resume"]].map((row) => <div className="application-row" key={row[0]}><div><strong>{row[0]}</strong><span>{row[1]}</span></div><StatusChip tone={row[2] === "Interview" ? "success" : row[2] === "Applied" ? "warning" : "neutral"}>{row[2]}</StatusChip><span className="muted data-number">{row[3]}</span><span>{row[4]}</span></div>)}</Panel></div>; }

export function InsightsView() { return <div className="view-stack"><PageHeader eyebrow="Judgment / Insights" title="Market signals" description="Emerging requirements around the kind of work you want next." /><div className="insight-grid"><Panel><p className="panel-kicker">Rising requirement</p><h2>Event-driven architecture</h2><p className="metric-large data-number">+34%</p><p>Appears more often in senior platform roles than 90 days ago.</p></Panel><Panel><p className="panel-kicker">Your alignment</p><h2>Strong foundation</h2><p className="metric-large data-number">84%</p><p>Your profile already contains evidence. Consider making it easier to find.</p></Panel></div><Panel><div className="section-heading"><div><p className="eyebrow">Evidence map</p><h2>Signals worth acting on</h2></div></div>{["Distributed systems", "Technical leadership", "Product discovery"].map((item, i) => <div className="list-row" key={item}><div><strong>{item}</strong><span>{i === 0 ? "Present in 68% of matched roles" : "Present in your profile"}</span></div><StatusChip tone={i === 0 ? "warning" : "success"}>{i === 0 ? "Surface" : "Covered"}</StatusChip></div>)}</Panel></div>; }

export function CoachView() { return <div className="view-stack coach-view"><PageHeader eyebrow="Judgment / AI Coach" title="Your career, with context." description="Ask about your profile, a role, or the next decision. Coach answers with the evidence it can see." /><Panel className="coach-surface"><div className="coach-intro"><Sparkles aria-hidden="true" /><h2>What should I focus on next?</h2><p>Try asking: “Which experience should I lead with for Northstar Labs?”</p></div><div className="coach-prompts"><button>Find my strongest evidence <ChevronRight aria-hidden="true" /></button><button>Explain my best current match <ChevronRight aria-hidden="true" /></button><button>What is missing from my profile? <ChevronRight aria-hidden="true" /></button></div></Panel></div>; }

export function SettingsView() { return <div className="view-stack settings-view"><PageHeader eyebrow="Utility" title="Settings" description="Quiet controls for your account and workspace." /><Panel><h2>Workspace preferences</h2><div className="settings-field"><label htmlFor="workspace-name">Workspace name</label><input id="workspace-name" defaultValue="Personal" /></div><div className="settings-field"><label htmlFor="email-updates">Email updates</label><select id="email-updates" defaultValue="important"><option value="important">Important updates only</option><option value="all">All activity</option><option value="none">None</option></select></div><button className="button-primary">Save preferences</button></Panel></div>; }
