'use client';
import { ArrowRight, Send } from 'lucide-react';
import { useState } from 'react';

import styles from './feedback-forms.module.css';

export function ContactForm(){return <MarketingForm kind="contact"/>}
export function FeedbackForm(){return <MarketingForm kind="feedback"/>}
function MarketingForm({kind}:{kind:'contact'|'feedback'}){const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle'); const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setState('sending');const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries());try{const res=await fetch(`${process.env.NEXT_PUBLIC_CAREEROS_API_URL??'http://localhost:3001'}/public/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok)throw new Error();setState('success');e.currentTarget.reset()}catch{setState('error')}};return <form className={styles.form} onSubmit={(event) => { void submit(event); }}><div className={styles.row}><label>Name<input name="name" required minLength={2}/></label><label>Email<input name="email" type="email" required/></label></div>{kind==='contact'&&<label>Subject<input name="subject" required minLength={2}/></label>}{kind==='feedback'&&<label>Feedback type<select name="type" defaultValue="General Feedback"><option>Feature Request</option><option>Bug</option><option>Improvement</option><option>General Feedback</option></select></label>}<label>Message<textarea name="message" required minLength={10}/></label><label className={styles.honeypot}>Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button disabled={state==='sending'} type="submit">{state==='sending'?'Sending…':kind==='contact'?'Send message':'Share feedback'} {kind==='contact'?<ArrowRight/>:<Send/>}</button>{state==='success'&&<p role="status">Thanks — your message has been sent.</p>}{state==='error'&&<p role="alert">We couldn&apos;t send that right now. Please try again.</p>}</form>}
